import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { DevtoolsServer } from "@frend-digital/next-dev-tools";
import { DT } from "@frend-digital/next-dev-tools/components";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const StoryblokContent = () => {
  return (
    <DT.Content>
      <DT.Text as="h2" variant="title">
        Storyblok
      </DT.Text>
      <DT.Button>Exit preview mode</DT.Button>
    </DT.Content>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <DevtoolsServer
          content={[
            {
              title: "Storyblok",
              icon: "X",
              content: <StoryblokContent />,
            },
          ]}
        />
      </body>
    </html>
  );
}
